### ISSUE TITLE
Error in training example

### ISSUE THREAD

**Issue by robmarkcole** [isaaccorley/torchrs#23]
Following the example from the README:
```
ValueError                                Traceback (most recent call last)
<ipython-input-11-f854c515c2ab> in <module>()
----> 1 trainer.fit(model, datamodule=dm)

23 frames
/usr/local/lib/python3.7/dist-packages/torchmetrics/functional/classification/stat_scores.py in _stat_scores_update(preds, target, reduce, mdmc_reduce, num_classes, top_k, threshold, multiclass, ignore_index)
    123         if not mdmc_reduce:
    124             raise ValueError(
--> 125                 "When your inputs are multi-dimensional multi-class, you have to set the `mdmc_reduce` parameter"
    126             )
    127         if mdmc_reduce == "global":

ValueError: When your inputs are multi-dimensional multi-class, you have to set the `mdmc_reduce` parameter
```

**Comment by isaaccorley** [comment]
That's odd. I made an example recently that uses the same setup under examples/levircd+.ipynb and didn't run into that error.

**Comment by robmarkcole** [comment]
I launched the `examples/levircd+.ipynb` straight to colab and hit exactly the same issue there.!

**Comment by isaaccorley** [comment]
Looks like the latest `torchmetrics==0.5.0` version required a new parameter for computing Accuracy, Precision, Recall on 2D segmentation mask output. Just had to add `mdmc_average="global"` to each of the metrics in the lightning modules. I'm able to train now so seems like it's fixed. See #25
