### ISSUE TITLE
probav training memory error

### ISSUE THREAD

**Issue by robmarkcole** [isaaccorley/torchrs#24]
Using colab pro with nominally 25 Gb I am still running out of memory at 17 epochs using your probav example notebook. Is there any way to free memory on the fly? I was able to train the tensorflow RAMS implementation to 50 epochs on colab pro

```
CUDA out of memory. Tried to allocate 46.00 MiB (GPU 0; 15.90 GiB total capacity; 14.01 GiB already allocated; 25.75 MiB free; 14.96 GiB reserved in total by PyTorch)
```

**Comment by isaaccorley** [comment]
I trained the model in the example on Colab with a Tesla T4 so maybe it gave you a different GPU?

Anyways, you cam decrease the batch_size and then increase accumulate_grad_batches to deal with this. Alternatively, you can reduce the num_res_blocks in the model.

**Comment by isaaccorley** [comment]
Strange. There must be a memory leak somewhere mayne in pytorch lightning? I'll look into this.

**Comment by isaaccorley** [comment]
1. Not sure why you are getting that behavior when changing thise params. If anything, that should free up more memory.
2. There is an early stopping callback. That os likely what is causing this. You can increase the patience param in the callback.

**Comment by robmarkcole** [comment]
Increasing from 5 to `patience=20` I managed to get an additional epoch before the memory error
