### ISSUE TITLE
Sydney Captions Dataset - Cannot retrieve the public link of the file.

### ISSUE THREAD

**Issue by singhal-shagun** [isaaccorley/torchrs#41]
Hi,

While trying to download the Sydney Captions dataset. `gdown` gives the following error:
```
FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Failed to retrieve file url:

        Cannot retrieve the public link of the file. You may need to change
        the permission to 'Anyone with the link', or have had many accesses.
        Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

You may still be able to access the file from the browser:

        https://drive.google.com/uc?id=1zAA8qG8FZLCj2t4t9JPgNS48sA2iltaU

but Gdown can't. Please check connections and permissions.
```

When I try to open `https://drive.google.com/uc?id=1zAA8qG8FZLCj2t4t9JPgNS48sA2iltaU` in the browser, Google Cloud gives me 404 error. 

Any suggestions how to download the Sydney Captions dataset?  Trying the Baidu route is a real pain.

**Comment by isaaccorley** [comment]
You can download it here https://mega.nz/folder/pG4yTYYA#4c4buNFLibryZnlujsrwEQ

**Comment by singhal-shagun** [comment]
Yeah. I did try that link. But its shows an empty folder:
![image](https://github.com/isaaccorley/torchrs/assets/20037489/055c34f8-fdbb-44a5-94f2-7a44c6394510)
![image](https://github.com/isaaccorley/torchrs/assets/20037489/8fbce5a9-8473-4e0b-8740-148ba5e46b11)

**Comment by isaaccorley** [comment]
I've rehosted the dataset here: https://huggingface.co/datasets/isaaccorley/Sydney-Captions
